### ISSUE TITLE
No longer able to find any gup.pe account from Pleroma

### ISSUE THREAD

**Issue by umonaca** [wmurphyrd/guppe#32]
When a user searches for a gup,pe account, it returns nothing on Pleroma, if the searched account has not been known or searched on the Pleroma server.

The reason is simple. The error log related is one line:
```
[error] Could not decode user at fetch https://gup.pe/u/board, {:content_type, "application/json; charset=utf-8"}
```

It means you will need to replace all `res.json` in `routes/user.js` with
```
res.set('Content-Type', 'application/activity+json');
res.send(payloadObject);
```

This bug occurs because `res.json` sets `Content-Type` to `application/json`, which is rejected by Pleroma. I am working on a similar express ActivityPub server and the solution above works.

**Comment by wmurphyrd** [comment]
I have this fixed with proper content negotiation in https://github.com/immers-space/activitypub-express , and I'll be converting guppe over to that that engine as soon as I get a chance, but I'm really short on time now. If you'd like to send a PR or be made a maintainer to handle this, I'd be glad

**Comment by goodevilgenius** [comment]
I was unable to find a group on both Pleroma and Mastodon.
