### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by FroehlichMarcel** [wmurphyrd/guppe#58]
Requests time out.

**Comment by wmurphyrd** [comment]
Looks like all the docker containers restarted recently, so there was indeed an outage. System memory was very low, but the delivery queue is all up-to-date, so I scaled back on the number of delivery workers to free up memory. 

Thanks for the report and please let me know if you have any problems in the future

**Comment by FroehlichMarcel** [comment]
Down again

**Comment by FroehlichMarcel** [comment]
Back on

**Comment by FroehlichMarcel** [comment]
Down again

**Comment by wmurphyrd** [comment]
Thanks for the reports. It seems we have a memory leak that is causing the process to restart regularly, only today it couldn't restart because of a dependency update chore I'd been putting off. Back for now


![image](https://user-images.githubusercontent.com/10034859/200061550-71235ada-2ef2-4a03-91ef-312a1568256e.png)

**Comment by FroehlichMarcel** [comment]
Down

**Comment by FroehlichMarcel** [comment]
Sadly, it is down most of the time. I'd really like to recommend this in various contexts, but it is too broken at the moment.
Anyway, thank you for providing this server and taking care.

**Comment by wmurphyrd** [comment]
Dear @FroehlichMarcel , I performed a major capacity upgrade last night, and it has run without issue since that time (21:30 on the chart below). I think you are safe to recommend Guppe. However, this is open-source and federated, so an even bigger help would be for you other others to host more their own Guppe instances so that the burden is not so concentrated. 

![image](https://user-images.githubusercontent.com/10034859/200193001-55a0e627-baf8-4fc2-b845-8d0f8fb491b0.png)
